#!/bin/bash

PATH=/usr/share/usbmount/:$PATH
COOKIE=/run/usbmount/
CNT=0

# unmount USB drive
eject() {
    usbmount remove "$i"
}

list() {
    echo -e "\tfstype\t\tdevname\t\tmountpoint"
    no=1
    for i in `ls $COOKIE`; do
        i="$COOKIE/$i"
        read fstype devname mountpoint < "$i"
        echo -e "$no.\t$devname\t$mountpoint\t$fstype"
        ((no = no + 1))
    done
    CNT=$no
}

loop() {
    list
}

usage() {
    cat << EOF
usbeject [-hli]
Eject usb device mounted by \`usbmount\`
    -h: show this page
    -l: list mounted usb device and mountpoint
    -i: run as interactive mode
No argument means eject all usb device listing.
EOF
}

if [ $# -le 0 ]; then
    for i in `ls $COOKIE/`; do
        echo "eject $i ..."
        eject "$i"
    done
    echo "done."
    exit 0
fi

while getopts "hli" opt; do
    case "$opt" in
        l)  list  ;;
        i)  loop  ;;
        h)  usage ;;
        *)  usage ;;
    esac
    shift
done
